"""Every sentence in this repository that somebody wrote, and who wrote it.

Five places here hold prose rather than data, and until this file only one of
them could be regenerated. `review-verdicts` drafts usecase-assessed.json from a
fact sheet and checks what comes back; the registry's 211 `note:` fields -- as
many words, and denser in figures that go stale -- had no path back through the
loop at all, nor did the viewer's help strings or the `_about` blocks.

    surface        what it is                              blocks
    usecase        research/usecase-assessed.json           155
    registry-note  every `note:`/`notes:` in models.yaml    211
    models-md      MODELS.md prose OUTSIDE a marker          48
    viewer-help    docs/index.html data-help, by element     18
    about          `_about` in the hand-written json         5

`models-md` is the odd one and is here as a PUNCH LIST rather than a drafting
target: that document is meant to be generated end to end from the registry and
research data, so a paragraph outside a `<!-- generated by -->` marker is work
somebody still owes a generator, not prose to have rewritten in place.

WHAT IS DELIBERATELY NOT HERE: the viewer's dynamic tooltips, which are template
literals assembled per cell from data and are closer to code than to prose;
python docstrings, for the same reason; and README/ROADMAP/CONTRIBUTING, which
are documents about the repository rather than blocks about a thing it carries,
with no per-block facts to check a claim against.

THE VALIDATOR IS THE SAME WHOEVER WROTE IT. That is the point of the file. A
draft coming back from an endpoint went through refusals and prose typed by hand
went through none, which is the wrong way round: the checks are about whether a
sentence is true and readable, not about who produced it.

Provenance lives in one ledger, `research/prose.json`, because most of these
surfaces have nowhere to put it -- a yaml `note:` is a string and an html
attribute is an attribute.
"""

import collections
import contextlib
import json
import os
import re
import shutil
import subprocess
import tempfile

import verdicts

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LEDGER = os.path.join(HERE, "prose.json")
ASSESSED = os.path.join(HERE, "usecase-assessed.json")
USECASE = os.path.join(HERE, "data", "usecase.json")
REGISTRY = os.path.join(ROOT, "registry", "models.yaml")
MODELS_MD = os.path.join(ROOT, "MODELS.md")
MODELS_MD_PROSE = os.path.join(HERE, "models-md.json")
VIEWER = os.path.join(ROOT, "docs", "index.html")
ABOUT_DIR = HERE
ABOUT_FILES = ["milestones.json", "quant-curves.json", "usecase-assessed.json",
               os.path.join("data", "proposals.json"),
               os.path.join("data", "sentiment-llm.json")]

# the file each surface's words live in, so they can be read as of a commit
SOURCE_PATHS = {"ASSESSED": "research/usecase-assessed.json",
                "REGISTRY": "registry/models.yaml",
                "MODELS_MD": "MODELS.md",
                "VIEWER": "docs/index.html"}

SURFACES = ["usecase", "registry-note", "models-md", "viewer-help", "about"]

# who wrote a block. `assistant` is this program in a session with a human
# reading along; `local` is the endpoint review-verdicts drafts through, which
# nobody reads until a human promotes it; `human` is typed by hand. the three
# are told apart rather than collapsed into "a model wrote it" because what a
# reader should do about the sentence differs: a `local` draft is unreviewed
AUTHORS = ("assistant", "local", "human")

# the fields of an assessed verdict that are prose. `confidence` and
# `assessed_on` are data about the block, not part of it
VERDICT_FIELDS = ("one_liner", "use_for", "avoid_for", "notes", "evidence")

# which blocks of the registry hold a note, and the order a path is built in.
# a note is attached to a thing -- a quant, a runtime, a whole model -- and the
# path has to say which, because `Qwen/Qwen3.8-27B` has four of them
NOTE_KEYS = ("note", "notes")
NESTED = ("quants", "components", "runtime", "speculative", "sampling",
          "turns", "thinking", "crispasr", "quant_sweep")

MARKER = re.compile(r"<!--\s*generated by (.+?)\s*-->")
END_MARKER = re.compile(r"<!--\s*end generated\s*-->")
HELP_TAG = re.compile(r'<\w+([^>]*\bdata-help="([^"]{20,})"[^>]*)>')
HELP_ID = re.compile(r'\bid="([^"]+)"')

# `grounded` is the registry repo a block is about, or None. `subject` is the
# (repo, quant) a registry note's references resolve against, which is NOT the
# block id: the id is keyed on the quant TAG so it survives a rung being
# renamed, and the size table is keyed on `file:` where the publisher does not
# name its types
Block = collections.namedtuple("Block", "surface id fields grounded subject")


def read_json(path, default=None):
    try:
        with open(path) as f:
            return json.load(f)
    except (IOError, ValueError):
        return {} if default is None else default


def ledger(path=LEDGER):
    """{block id: {author, written_on, authored_against}}."""
    return read_json(path).get("blocks") or {}


# -- the surfaces ------------------------------------------------------------

def _usecase_blocks():
    assessed = read_json(ASSESSED).get("assessed") or {}
    out = []
    for repo, blk in sorted(assessed.items()):
        fields = {}
        for name in VERDICT_FIELDS:
            v = blk.get(name)
            if isinstance(v, list):
                v = "\n".join(v)
            if v:
                fields[name] = v
        if fields:
            out.append(Block("usecase", "usecase:" + repo, fields, repo, None))
    return out


def snapshot_for(repo, led=None):
    """The figures a verdict was written against, from the one ledger.

    usecase-assessed.json carried this inline and no other surface could, so
    the record moved here and the field came out of that file. Kept as one
    function because three callers ask the same question.
    """
    return ((led if led is not None else ledger()).get("usecase:" + repo)
            or {}).get("authored_against")


def _rung_key(entry):
    """What names a quant or component entry, since its position does not.

    A ladder gains a rung and every index after it shifts, which would rename
    somebody else's block and lose its provenance. The repo and the tag are what
    the entry IS, and lint already refuses two entries sharing them.
    """
    return "%s:%s" % (entry.get("repo") or "?",
                      entry.get("quant") or entry.get("file") or "?")


def urls_beside(block):
    """Urls the note's OWN block carries, which are a source it need not repeat.

    A `runtime.note` sits beside `tracking:`, `fork:` or `patch:`, each of which
    is a link to the pull request the sentence is about. The note is grounded by
    the structure it hangs off, and asking it to cite the url a field beside it
    already holds would be two copies of one fact.
    """
    return sorted(v for k, v in (block or {}).items()
                  if isinstance(v, str) and v.startswith("http"))


def own_facts(node):
    """{key: value} of the block a note sits in, without the note or what nests.

    A sampling note is about the profile beside it -- its `source` and its values
    -- and a drafter shown only the field name invented them: kimi k3's draft said
    the profile fell back to llama.cpp defaults where it is `tuned-here`.
    """
    return {k: v for k, v in node.items()
            if k not in NOTE_KEYS and (not isinstance(v, (dict, list))
                                       or (isinstance(v, list)
                                           and all(not isinstance(i, (dict, list)) for i in v)))}


def _walk_notes(node, repo, path, out, subject=None, entry=None):
    """Every note under one model, keyed by where it hangs.

    The path is built from the containers on the way down rather than from the
    field name, because `note` appears at six depths and the one on a quant is
    about a FILE while the one on the model is about the model. `subject` is
    what a reference in it resolves against, and it is carried down separately
    from the path: the path names the rung by TAG so the id is stable, while a
    lookup goes through `file:` wherever the publisher does not name its types.
    """
    if isinstance(node, dict):
        for key, value in node.items():
            if key in NOTE_KEYS and isinstance(value, str):
                at = ".".join(path + [key]) if path else key
                out.append(Block("registry-note", "registry-note:%s#%s" % (repo, at),
                                 {"note": value}, repo,
                                 dict(subject or {"repo": repo, "quant": None},
                                      entry=entry, beside=urls_beside(node),
                                      node=own_facts(node))))
            elif isinstance(value, (dict, list)):
                _walk_notes(value, repo, path + [key] if key in NESTED else path,
                            out, subject, entry)
    elif isinstance(node, list):
        for item in node:
            where, at = path, subject
            if path and isinstance(item, dict):
                where = path[:-1] + ["%s[%s]" % (path[-1], _rung_key(item))]
                if item.get("repo"):
                    # both keys, in build-viewer's order: the size table holds
                    # the tag where the filenames carry one and the filename
                    # where they do not, and a pin may name either or both
                    at = {"repo": item["repo"], "pin": item,
                          "quant": [k for k in (item.get("file"),
                                                item.get("quant")) if k]}
            _walk_notes(item, repo, where, out, at, entry)


def _registry_blocks():
    import yaml
    with open(REGISTRY) as f:
        models = (yaml.safe_load(f) or {}).get("models") or {}
    out = []
    for repo, model in sorted(models.items()):
        _walk_notes(model, repo, [], out, entry=model)
    return out


def _models_md_blocks():
    """The paragraphs MODELS.md still holds by hand.

    Everything in that document is meant to come out of the registry and the
    research data through a `<!-- generated by -->` marker, so this enumerates
    what has not been given a generator yet. Tables and html are not prose and
    are not counted; a numbered list item is, because the picks were argued in
    them.

    A marked block ends two ways and refresh-tables has always known both: a
    table stops where its pipes stop, and only a generator emitting PROSE needs
    an explicit end marker. Reading every marker as opening a region until the
    next end marker let the ranking table swallow the five hundred hand-written
    lines below it, so those sections reported as already generated.
    """
    with open(MODELS_MD) as f:
        lines = f.read().split("\n")
    hand, i = [], 0
    while i < len(lines):
        if not MARKER.search(lines[i]):
            hand.append(lines[i])
            i += 1
            continue
        closes = next((j for j in range(i + 1, len(lines))
                       if END_MARKER.search(lines[j])), None)
        if closes is not None and not any(MARKER.search(lines[j])
                                          for j in range(i + 1, closes)):
            i = closes + 1
            continue
        i += 1
        while i < len(lines) and not lines[i].startswith("|"):
            hand.append(lines[i])
            i += 1
        while i < len(lines) and lines[i].startswith("|"):
            i += 1

    # keyed on the heading it sits under and its place within it, not on a line
    # number: a paragraph added anywhere above would renumber every block below
    # it and orphan their provenance
    out, para, heading, nth = [], [], "top", 0

    def flush():
        text = " ".join(para)
        if text and not text.lstrip().startswith(("|", "<", "```")):
            out.append(Block("models-md", "models-md:%s#%d" % (heading, nth),
                             {"text": text}, None, None))
            return True
        return False

    for line in hand + [""]:
        if line.startswith("#"):
            if para and flush():
                nth += 1
            para = []
            heading = re.sub(r"[^a-z0-9]+", "-", line.lstrip("# ").lower()).strip("-")
            nth = 0
            continue
        if line.strip():
            para.append(line.strip())
            continue
        if para and flush():
            nth += 1
        para = []
    return out + _stored_md_blocks()


def _stored_md_blocks():
    """Sections of MODELS.md that have moved out of the document and into source.

    A paragraph keeps the id it had while it was still typed into the markdown,
    so the ledger row naming who wrote it survives the move. What it gains is a
    SUBJECT: once the section says which model it is about, its figures are
    references a build resolves against that model's facets, instead of digits
    that cannot be re-read once the capture moves under them.

    A body entry given as a LIST is layout -- a table, a bullet list -- and is
    numbered past rather than counted, which is the rule the document already
    follows. Otherwise migrating a section that interleaves tables with prose
    would renumber every paragraph after the first table and orphan its row.
    """
    stored = read_json(MODELS_MD_PROSE).get("sections") or {}
    out = []
    for slug, section in sorted(stored.items()):
        nth = 0
        for text in section.get("body") or []:
            if isinstance(text, list):
                continue
            out.append(Block("models-md", "models-md:%s#%d" % (slug, nth),
                             {"text": text}, section.get("subject"), None))
            nth += 1
    return out


def _viewer_blocks():
    """The help strings a reader hovers, keyed on the control they hang off.

    Only the ones on an element with an id. The other fourteen are built inside
    template literals per table cell, from the row's own data -- they are code
    that happens to emit words, and there is no block of them to rewrite.
    """
    with open(VIEWER) as f:
        html = f.read()
    out = []
    for attrs, text in HELP_TAG.findall(html):
        found = HELP_ID.search(attrs)
        if not found:
            continue
        out.append(Block("viewer-help", "viewer-help:" + found.group(1),
                         {"help": text}, None, None))
    return out


def _about_blocks():
    out = []
    for name in ABOUT_FILES:
        path = os.path.join(ABOUT_DIR, name)
        text = read_json(path).get("_about")
        if not text:
            continue
        if isinstance(text, list):
            text = "\n".join(text)
        out.append(Block("about", "about:" + name.replace(os.sep, "/"),
                         {"about": text}, None, None))
    return out


READERS = {"usecase": _usecase_blocks, "registry-note": _registry_blocks,
           "models-md": _models_md_blocks, "viewer-help": _viewer_blocks,
           "about": _about_blocks}


def blocks(surface=None):
    """Every prose block on one surface, or on all of them."""
    if surface:
        return READERS[surface]()
    return [b for s in SURFACES for b in READERS[s]()]


def _from_git(rev, rel, into):
    """One source file as of `rev`, on disk. Missing there means it is new."""
    out = os.path.join(into, rel)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    got = subprocess.run(["git", "show", "%s:%s" % (rev, rel)], cwd=ROOT,
                         stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                         text=True)
    with open(out, "w") as f:
        f.write("" if got.returncode else got.stdout)
    return out


@contextlib.contextmanager
def as_committed(rev="HEAD"):
    """Read every surface as of a commit, to see which prose has been rewritten.

    The readers take their paths from module constants rather than arguments,
    so this swaps the constants at a checkout of the five source files instead
    of threading a revision through all of them. Nothing else in the module
    holds a path open across the block.
    """
    tmp = tempfile.mkdtemp(prefix="prose-")
    saved = dict(globals())
    try:
        for name, rel in SOURCE_PATHS.items():
            globals()[name] = _from_git(rev, rel, tmp)
        for name in ABOUT_FILES:
            _from_git(rev, "research/" + name.replace(os.sep, "/"), tmp)
        globals()["ABOUT_DIR"] = os.path.join(tmp, "research")
        yield
    finally:
        for name in list(SOURCE_PATHS) + ["ABOUT_DIR"]:
            globals()[name] = saved[name]
        shutil.rmtree(tmp, ignore_errors=True)


# -- the validator, which does not care who wrote the prose ------------------

# words that sound like a claim and make none. the list is CLAUDE.md's, which is
# the style this repository is written in
MARKETING = re.compile(
    r"\b(delve|leverag(?:e|es|ed|ing)|seamless(?:ly)?|robust(?:ly)?|crucial(?:ly)?|"
    r"showcas(?:e|es|ed|ing)|elevat(?:e|es|ed|ing)|cutting[- ]edge|game[- ]chang\w*|"
    r"unlock(?:s|ed|ing)?|empower(?:s|ed|ing)?)\b", re.I)
# openers that spend a line saying a line is coming
FILLER = re.compile(
    r"(?:^|(?<=[.;]\s))\s*(?:it(?:'s| is) worth noting|moreover|furthermore|"
    r"in conclusion|that (?:being )?said|needless to say|at the end of the day)\b", re.I)
# "not just x, it's y" and its relatives -- the shape, not the words
ANTITHESIS = re.compile(r"\bnot (?:just|only|merely)\b[^.]{0,80}?,\s*(?:it|this|that)"
                        r"(?:'s| is| was)\b", re.I)
NON_ASCII = re.compile(r"[^\x00-\x7f]")


def quote_id(text):
    """Re-exported so a caller has one import rather than two."""
    return verdicts.quote_id(text)


def check_text(text, facets=None):
    """[why] -- everything wrong with one piece of prose, whoever wrote it.

    Returns a list rather than the first failure, because the point is a punch
    list: a block with three problems should be reported once with three, not
    three times with one.

    `facets` is what the block is allowed to cite. Where a surface has none --
    a help string is about the page, not about a model -- the citation checks
    are skipped and the style checks are not, which is the whole reason they
    are in one function.
    """
    text = text or ""
    out = []
    bad = NON_ASCII.findall(text)
    if bad:
        out.append("is not ascii: %s" % ", ".join(sorted(set(bad))))
    bad = MARKETING.findall(text)
    if bad:
        out.append("uses %s" % ", ".join(sorted({b.lower() for b in bad})))
    if FILLER.search(text):
        out.append("opens with filler: %r" % FILLER.search(text).group().strip())
    if ANTITHESIS.search(text):
        out.append("writes the not-just-x-it's-y shape: %r"
                   % ANTITHESIS.search(text).group().strip())
    if facets is None:
        return out

    typed = verdicts.TYPED_PCT.findall(verdicts.CITE_REF.sub("", text))
    if typed:
        out.append("types %s instead of citing the facet"
                   % ", ".join(sorted(set(typed))))
    ok, why = verdicts.check_quoted(text, facets)
    if not ok:
        out.append(why)
    unknown = [i for i in verdicts.CITE_REF.findall(text)
               if verdicts.evidence_line(i, facets) is None]
    if unknown:
        out.append("cites %s, which this model does not carry"
                   % ", ".join(sorted(set(unknown))))
    return out


def facts_for(block, models=None):
    """The facets a block may cite, or None where the surface has no facts.

    A registry note is grounded too, but on different evidence: it is about a
    FILE, so it cites sizes and the publisher's own card rather than a
    percentile against a cohort. research/notes.py holds that vocabulary and
    checks it, which is why this returns None for that surface rather than an
    empty dict -- None turns the FACET checks off and leaves the style ones on.
    """
    if block.surface not in ("usecase", "models-md") or not block.grounded:
        return None
    if models is None:
        models = read_json(USECASE).get("models") or {}
    return ((models.get(block.grounded) or {}).get("facets")) or {}


def check(block, models=None, note_data=None):
    """[(field, why)] for one block, on whichever vocabulary grounds it.

    The style checks run over every surface and the grounding checks run over
    the one that has a grounding. Which vocabulary applies is a property of the
    SURFACE and never of who wrote the words.
    """
    facts = facts_for(block, models)
    out = [(name, why) for name, text in sorted(block.fields.items())
           for why in check_text(text, facts)]
    if block.surface == "registry-note":
        import notes
        data = note_data if note_data is not None else notes.load()
        at = block.subject or {}
        out += [(name, why) for name, text in sorted(block.fields.items())
                for why in notes.check(text, at.get("repo") or block.grounded,
                                       at.get("quant"), data, model=block.grounded,
                                       beside=at.get("beside") or (),
                                       pin=at.get("pin"),
                                       entry=at.get("entry"))]
    return out
